name: Daily Job

on:
  schedule:
    - cron: "10 1,10,22 * * *" 
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap
        
    - name: Run Multitest Script
      #working-directory: zubo/speedtest
      run: |
       cd $GITHUB_WORKSPACE/speedtest
        bash ./tv.sh
        
    - name: Update Results
      run: |
        cd $GITHUB_WORKSPACE/speedtest
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update results"
        git push
